version: 0.2

env:
  variables:
    S3_BUCKET: "fitbody-bucket-1"
    EC2_HOST: "54.167.250.60"
    SECRET_NAME: "ssh"

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install -g pm2

      - echo Fetching SSH key from Secrets Manager...
      - mkdir -p /root/.ssh
      - aws secretsmanager get-secret-value --secret-id ${SECRET_NAME} --query SecretString --output text > /tmp/secret.txt
      - sed 's/{"ssh":"//;s/"}//' /tmp/secret.txt > /root/.ssh/id_rsa
      - chmod 600 /root/.ssh/id_rsa
      
  pre_build:
    commands:
      - echo Running for frontend...
      - npm install
      
  build:
    commands:
      - echo Building frontend...
      - npm run build

      - echo Running for backend...
      - cd server/
      - npm install

  post_build:
    commands:
      - echo Build completed

      - echo Deploying frontend to S3...
      - cd ../
      - aws s3 cp dist s3://${S3_BUCKET} --recursive

      - echo Deploying backend to EC2...
      - ssh -o StrictHostKeyChecking=no -i /root/.ssh/id_rsa ec2-user@${EC2_HOST} 'cd /home/ec2-user/FitBody/server && git pull origin main && npm install && pm2 startOrRestart index.js --name FitBody'
      - echo Build completed on `date`


artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
