version: 0.2

env:
  variables:
    S3_BUCKET: "fitbody-bucket-1"

phases:
  install:
    commands:
      - echo Installing dependencies...
      - npm install -g pm2

  pre_build:
    commands:
      - echo Running for frontend...
      - rm -rf node_modules package-lock.json
      - npm install
      
  build:
    commands:
      - echo Building frontend...
      - npm run build

  post_build:
    commands:
      - echo Build completed

      - echo Deploying frontend to S3...
      - aws s3 cp dist s3://${S3_BUCKET} --recursive

artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
