version: 0.2
env:
  variables:
    S3_BUCKET: "fitbody-bucket"

phases:
  install:
    commands:
      - echo Installing dependencies...
      
  pre_build:
    commands:
      - echo Running for frontend...
      - npm install
      
  build:
    commands:
      - echo Building frontend...
      - npm run build

  post_build:
    commands:
      - echo Build completed
      # - echo Packaging frontend artifacts...
      # - cp -r dist/* .
      # - aws s3 sync ./dist $S3_BUCKET
      - aws s3 cp dist/* s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`

artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
