version: 0.2

env:
  variables:
    S3_BUCKET: "fitbody-bucket-1"

phases:
  install:
    commands:
      - echo Installing dependencies...
      
  pre_build:
    commands:
      - echo Running for frontend...
      - npm install
      
  build:
    commands:
      - echo Building frontend...
      - npm run build

  post_build:
    commands:
      - echo Build completed
      - aws s3 cp dist s3://${S3_BUCKET} --recursive
      - echo Build completed on `date`

artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
