AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  AppName:
    Type: String
    Default: FitBody-Amplify
  GitHubToken:
    Type: String
    Description: The GitHub OAuth token stored in AWS Systems Manager Parameter Store
    Default: /github/oauth/token
  Repository:
    Type: String
    Default: https://github.com/KaziNizamul/FitBody
    Description: The URL of your GitHub repository
  BranchName:
    Type: String
    Default: main
    Description: The branch name of your GitHub repository

Resources:
  AmplifyApp:
    Type: AWS::Amplify::App
    Properties:
      Name: !Ref AppName
      Repository: !Ref Repository
      OauthToken: !Ref GitHubToken
      EnvironmentVariables:
        - Name: NODE_ENV
          Value: production
      BuildSpec: |
        version: 1.0
        frontend:
          phases:
            preBuild:
              commands:
                - npm install
            build:
              commands:
                - npm run build
          artifacts:
            baseDirectory: dist
            files:
              - '**/*'
        backend:
          phases:
            preBuild:
              commands:
                - cd server
                - npm install
            build:
              commands:
                - echo "Backend build complete."
          artifacts:
            baseDirectory: server
            files:
              - '**/*'

  AmplifyBranch:
    Type: AWS::Amplify::Branch
    Properties:
      AppId: !Ref AmplifyApp
      BranchName: !Ref BranchName
      EnableAutoBuild: true
      BasicAuthConfig:
        EnableBasicAuth: false

  AmplifyBackendEnvironment:
    Type: AWS::Amplify::BackendEnvironment
    Properties:
      AppId: !Ref AmplifyApp
      EnvironmentName: dev
      StackName: amplify-dev

  AmplifyRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: amplify.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: AmplifyPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - amplify:*
                Resource: '*'

Outputs:
  AmplifyAppId:
    Description: The ID of the Amplify app
    Value: !Ref AmplifyApp
  AmplifyAppUrl:
    Description: The URL of the Amplify app
    Value: !GetAtt AmplifyApp.DefaultDomain
