AWSTemplateFormatVersion: '2010-09-09'
Resources:
  CodeCommitRepository:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: FitBody-CodeCommit-Repo
      RepositoryDescription: My CodeCommit repository

  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: FitBody-CodeBuild
      Source:
        Type: CODECOMMIT
        Location: !GetAtt CodeCommitRepository.CloneUrlHttp
      Environment:
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:4.0
        Type: LINUX_CONTAINER
      ServiceRole: arn:aws:iam::your-account-id:role/service-role/AWSCodeBuildServiceRole ##

  CodePipeline:
    Type: AWS::CodePipeline::Pipeline
    Properties:
      Name: FitBody-CodePipeline
      RoleArn: arn:aws:iam::your-account-id:role/service-role/AWSCodePipelineServiceRole ##
      ArtifactStore:
        Type: S3
        Location: your-artifact-store-bucket ##
      Stages:
        - Name: Source
          Actions:
            - Name: Source
              ActionTypeId:
                Category: Source
                Owner: AWS
                Provider: CodeCommit
                Version: '1'
              OutputArtifacts:
                - Name: SourceOutput
              Configuration:
                RepositoryName: !Ref CodeCommitRepository
                BranchName: master
        - Name: Build
          Actions:
            - Name: Build
              ActionTypeId:
                Category: Build
                Owner: AWS
                Provider: CodeBuild
                Version: '1'
              InputArtifacts:
                - Name: SourceOutput
              OutputArtifacts:
                - Name: BuildOutput
              Configuration:
                ProjectName: !Ref CodeBuildProject
