name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

  deploy_frontend:
    name: Deploy Frontend to S3
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      # - name: Deploy to S3
      #   uses: mirrorweb/s3-sync-action@master
      #   with:
      #     args: --acl public-read --follow-symlinks --delete
      #   env:
      #     SOURCE_DIR: 'dist'
      #     AWS_REGION: 'us-east-1'
      #     AWS_S3_BUCKET: 'fitbody-frontend-build-file'
      #     AWS_ACCESS_KEY_ID: 'ASIA6ISTANZUHKPCO2WD'
      #     AWS_SECRET_ACCESS_KEY: 'vaenrR+NNARkO81BRsbLeOEpbIOFeRnpvYOlWZ9Z'
      #     AWS_GHA_ROLE: 'arn:aws:iam::980500377192:role/LabRole'
        
      - name: Deploy to S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: 'ASIA6ISTANZUHKPCO2WD'
          aws-secret-access-key: 'vaenrR+NNARkO81BRsbLeOEpbIOFeRnpvYOlWZ9Z'
          aws_session_token: 'IQoJb3JpZ2luX2VjEEcaCXVzLXdlc3QtMiJGMEQCIG5Hx4CxJhzpczQP6SYHPJ5P2tFHr1pRe9aogHrt/CCUAiADXYNLYmdG9A0+sb9JClIW1xGs0Sgl7y5UUI/jTE2tpSqmAggwEAEaDDk4MDUwMDM3NzE5MiIMtaCxvuMKMlWPpaaiKoMCZP6OngNOmlT+qyol5XX6peZCnHy5Gichr07AkTI82R61v2lmgORPgjOf+8fBcpeC28H5LgU96UlJiA8rZn7T8jNIvGYK7kvqNHTb3jSUn8zAS8+/KVtQyFTAGgi4s+GcQmG4eN1NlDeSviw3AY4Gfr2tkyUADAFRbZtgQxXLupLRF4RyapbJqwslXH5hX83cNbIhTVWaX8kOQZ9DyjDUOJbT53f7sUkd3AmxZTPrZomV132Tt+ko8MZDRMCMkS/k8TeqbrBGy0CVoDxEJ0yD9mcqL6OAUewwKo9mOk4rVsq7qj3uCjwSxaGAUd3z7wXHYnArzoTIitDZAU3PdqiNx9FhpTDezJ61BjqeARC4FD0Wp/F2PaCO9R4STIw2KyB2ORY3foACXxsCqMsQLy1/MZkqIXjBL7Y/jQbvnhoEMBJ9Ir1Evzx3s33171Ki5ZIdVjxXP2d1DvmGJmD+dV09lb2X/egasK8oot4oM0YGxb2EqVyzbfezbgydNtmWnahMSQjrrtNJEz7uFWuk2NerqUzJg/2Xv7t4g0V+sWGeDJiPWWadcGj3b5Su'
          aws-region: 'us-east-1'

      - name: Sync files to S3
        run: aws s3 sync dist/ s3://fitbody-frontend-build-file --acl public-read --delete

      # - name: Deploy to S3
      #   uses: drewble/s3-upload-github-action@0.1.4
        # with:
        #   args: --acl public-read --follow-symlinks --delete
        # env:
        #   AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        #   AWS_ACCESS_KEY_ID: ASIA6ISTANZUO7MCIAFO
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   # AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        #   # AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
        #   SOURCE_DIR: 'dist'
        # env:
        #   FILE: dist/
        #   S3_ENDPOINT: 'fitbody-frontend-build-file.s3-website-us-east-1.amazonaws.com'
        #   S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        #   S3_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        #   S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

       
          
  deploy_backend:
    name: Deploy Backend to EC2
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/FitBody/server
            git pull origin main
            npm install
            pm2 restart all