name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

  deploy_frontend:
    name: Deploy Frontend to S3
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Build
        run: npm run build

      - name: Deploy to S3
        uses: drewble/s3-upload-github-action@0.1.4
        # with:
        #   args: --acl public-read --follow-symlinks --delete
        # env:
        #   AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        #   AWS_ACCESS_KEY_ID: ASIA6ISTANZUO7MCIAFO
        #   AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        #   # AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        #   # AWS_S3_ENDPOINT: ${{ secrets.AWS_S3_ENDPOINT }}
        #   SOURCE_DIR: 'dist'
        env:
          FILE: dist/
          S3_ENDPOINT: 'http://fitbody-frontend-build-file.s3-website-us-east-1.amazonaws.com'
          S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          S3_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          S3_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          
  deploy_backend:
    name: Deploy Backend to EC2
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd /home/ec2-user/FitBody/server
            git pull origin main
            npm install
            pm2 restart all